### ISSUE TITLE
Sensors updates only once an hour. 

### ISSUE THREAD

**Issue by zylxpl** [skelgaard/homeassistant-apsystems#12]
Hi everyone,
 Sensor updates only once per hour. Because of that it is hard to do anything useful with the data. Can we somehow increase pooling rate?

**Comment by synack666** [comment]
right, this took me to look around, found this and feel happy:

https://github.com/ksheumaker/homeassistant-apsystems_ecur

**Comment by zylxpl** [comment]
@synack666 sure, but this is much harder to implement for me, as the HA server is not connected via LAN directly to ECU.

**Comment by synack666** [comment]
No problem, same here, my HA server is connected via Lan to my router, ECU ist connected via WLAN to my router, works fine.

**Comment by synack666** [comment]
they have to be in the same network, thats all

**Comment by zylxpl** [comment]
@synack666 connection method is irrelevant, i meant that my HA server and ecu are not on the same local network and are not evn in the same location.  To get this work i would need to create some vpn between two locations.

**Comment by synack666** [comment]
right, now i understand :-)

**Comment by skelgaard** [comment]
it does pull more than once per hour, but the energy dashboard doesn't update more than once per hour... so it matters where you want it to show ?
If you need live data, you can't do it with this, as the apsystem doesn't give data that way. its set to request every 20 sec, so it can be lowered, but shouldn't be much better..
if you want live data then as @synack666 says that addon is better (though i can't get my ECUR to give me that interface) or get a shelly 3em and add that to the outputs from the solar and messure with that live what it produces

**Comment by zylxpl** [comment]
@skelgaard I'm not referring to Energy dashboard, don't using it anyway. What is a problem for me is that apsystems sensors update once hour on even less. Here is a sample readout of apsystems_energy_day:

![image](https://user-images.githubusercontent.com/13242378/163679271-aedd69c1-6498-4aa7-8331-69bea8d7899a.png)

As you can see it only updates once a hour. Around 13.30 i restarted HA and  got the current value for that time. So the data is accessible.

**Comment by didigrand** [comment]
@skelgaard @ylxpl I have the exact same issue...
The apsystems_energy_day updates only once an hour.
But when I look at the log, the automation run every 5 minutes.
