### ISSUE TITLE
IDK Some Errors

### ISSUE THREAD

**Issue by MORITZ0405** [skelgaard/homeassistant-apsystems#17]
![noooooot](https://user-images.githubusercontent.com/60063969/203156227-bb673879-e543-429b-ad97-324c1ae026cd.PNG)
What is this ?

**Comment by skelgaard** [comment]
well the code in the 1.0.6 is not the code in the repository.... hmmm...

pushed a 1.0.7 and checked... the new code is in it

**Comment by MORITZ0405** [comment]
THX
