### ISSUE TITLE
no sensors

### ISSUE THREAD

**Issue by devano1701** [skelgaard/homeassistant-apsystems#18]
Still not working for me. I got this error earlier before the problems with the website. Until now it has never worked for me. I don't see the sensors. I get this error message:

Logger: homeassistant.components.sensor
Source: custom_components/apsystems/sensor.py:247 
Integration: Sensor (documentation, issues) 
First occurred: 09:40:45 (5 occurrences) 
Last logged: 09:40:53

apsystems: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 703, in async_device_update
    await task
  File "/config/custom_components/apsystems/sensor.py", line 142, in async_update
    ap_data = await self._fetcher.data()
  File "/config/custom_components/apsystems/sensor.py", line 247, in data
    timestamp_event = int(self.cache['time'][-1]) + offset_hours  # apsystems have 8h delayed in timestamp from UTC
TypeError: 'NoneType' object is not subscriptable

Maybe my timezone is not correct, but I don't know what to do.
Please advice.

**Comment by MORITZ0405** [comment]
turn sunset off

**Comment by daniel1204xx** [comment]
Same issue for me .. I'm not able to get it running again ;(

**Comment by devano1701** [comment]
It seems that in line 247 the value of self.cache is None.
But why?

**Comment by skelgaard** [comment]
which version are you on cause i do not have that in 247 in mine, which suggest an older unupdated version.

**Comment by skelgaard** [comment]
your self.cache is empty cause there is no data from that day from the system.

if you login at https://www.apsystemsema.com it will say 0 for today, therefor no data... 
i will se, i fix so it doesn't give an error on that, but it is of no matter for the system.
If there should be data, then you need to check your modem is up and if the ema has data, do write again, i will look futher for error then

**Comment by devano1701** [comment]
I use version 1.0.7 and line 247 is: “timestamp_event = int(self.cache['time'][-1]) + offset_hours  # apsystems have 8h delayed in timestamp from UTC”

The error message is:

Logger: homeassistant.components.sensor
Source: custom_components/apsystems/sensor.py:247 
Integration: Sensor (documentation, issues) 
First occurred: 14:05:42 (5 occurrences) 
Last logged: 14:05:51

apsystems: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in async_device_update
    await task
  File "/config/custom_components/apsystems/sensor.py", line 142, in async_update
    ap_data = await self._fetcher.data()
  File "/config/custom_components/apsystems/sensor.py", line 247, in data
    timestamp_event = int(self.cache['time'][-1]) + offset_hours  # apsystems have 8h delayed in timestamp from UTC
TypeError: 'NoneType' object is not subscriptable

Self.cache is empty because the response is 204 No Content.

After 5 occurrences (the 5 sensors ?) there are no more errors. I presume the process is stopped.

I don’t see any sensors from apsystems in HA.

When I access the website or use the app I do see content.

**Comment by devano1701** [comment]
When I restart HA in the evening (I am living in NL) with sunset on, the sensor is not running. But now I see the 5 sensors from apsystems, but they are all not available.
Maybe this gives you a clue.

**Comment by skelgaard** [comment]
the sensors are unavaliable untill there is data... when suset is on, it doesn't fetch data after the sun has gone down.
they will not be up before first data the next day.

**Comment by devano1701** [comment]
But on day time I get those errors because there is no content and the sensors stay unavailable.

**Comment by skelgaard** [comment]
can you see any power generated on the ema site ? 

try the commands in https://github.com/skelgaard/homeassistant-apsystems/issues/15#issuecomment-1322361350

i have pushed a new version, that should remove the errors in the log for no data, as it isn't really an error.

**Comment by devano1701** [comment]
Oke, I am not a real expert.

On the GET the response is 200, with a lot of content.

On the POST the response is 204, with the message: The content type of response is application/json, while response body is not a valid json string

I am using REST Client in VS Code.

Maybe I didn’t format the POST correctly.

**Comment by skelgaard** [comment]
204 means no data.

if you go into the ema is any production from today ?

**Comment by devano1701** [comment]
Yes,

I see production on the website and in the app.

**Comment by skelgaard** [comment]
if you get 204 in vscode, there either is no data or you may have added wrong keys in it

**Comment by devano1701** [comment]
There sure is data, so something must be wrong with the POST.
As I mentioned, I am not an expert.
I did check the keys, they are ok.
I presume my POST command is not correctly formatted.
I will get some local help tomorrow and try again.
For now: thanks a lot for the support so far.
