### ISSUE TITLE
Energy Dashboard statistics?

### ISSUE THREAD

**Issue by RacerBas** [skelgaard/homeassistant-apsystems#20]
I'm trying to add the solar panels to the energy dasboard but it doesn't seem to be supported?

https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

Is this possible perhaps?

**Comment by skelgaard** [comment]
mine is in my dashboard... what are you missing ?

**Comment by RacerBas** [comment]
on the built-in energy dashboard you cannot add it into the solar production category. It's just not listed
![image](https://user-images.githubusercontent.com/1407767/207790990-c2baaef9-3395-4d07-81ed-6135656876b7.png)

**Comment by skelgaard** [comment]
ah i can se i have this in my configuration... i will look into if i can get that set by default in the sensors
homeassistant:
  customize_glob:
    sensor.apsystems_energy_day:
      device_class: energy
      state_class: total_increasing

**Comment by Bittabola** [comment]
Hi, has this been resolved? I don’t see the APsystems sensors in the dropdown when I click Add Solar Production. Thanks!

**Comment by icecreamfarmer** [comment]
> Hi, has this been resolved? I don’t see the APsystems sensors in the dropdown when I click Add Solar Production. Thanks!

For me the same. Have been trying different yaml configs but I'll keep getting errors that the device class is not valid.

**Comment by icecreamfarmer** [comment]
> Hi, has this been resolved? I don’t see the APsystems sensors in the dropdown when I click Add Solar Production. Thanks!

I Think you need to add that line or device class somewhere in here:
/config/custom_components/apsystems/sensor.py

Bu i can't get it to work.

**Comment by skelgaard** [comment]
have you tried the code in configuration.yaml ?
i have not found out how to add this into the code, so that code in configuration is not needed.

**Comment by icecreamfarmer** [comment]
> have you tried the code in configuration.yaml ? i have not found out how to add this into the code, so that code in configuration is not needed.

Yes and keep getting errors like:
Invalid domain sensor.apsystems_energy_day

**Comment by icecreamfarmer** [comment]
> have you tried the code in configuration.yaml ? i have not found out how to add this into the code, so that code in configuration is not needed.

Let's put it this way. What exactly did you put into the config.yaml and where?

**Comment by Bittabola** [comment]
I added the following code to configutation.yaml in the config folder:

`sensor:
  - platform: apsystems
    authId: 2c9f934a884b9324018858f15XXXXXX
    systemId: 2c9f934a884b93240188587XXXXXX
    ecuId: 2162XXXXXXX
    sunset: off`

**Comment by skelgaard** [comment]
Seems i have fixed this in the next version that i will proberly release tomorrow... just doing final testings of it
