### ISSUE TITLE
Moar datas?

### ISSUE THREAD

**Issue by Duxaat** [skelgaard/homeassistant-apsystems#26]
Hello,

First nice job! I implemented this in HA, it works like a charm, tho i'd like to add a few datas like total_month and total_year.
I can't find documentation on APS api, so i'm clueless about what Ajax calls should be made in order to retrieve those datas.
Any help would be appreciated.

**Comment by skelgaard** [comment]
well actually there is no documentation on their calls... so there is only one way... go look what their website does of calls, and then try to replicate it in postman or the likings.
But if your system has run, then that data should be in home assistant already,
