### ISSUE TITLE
APsystems not appearing as a device

### ISSUE THREAD

**Issue by Bittabola** [skelgaard/homeassistant-apsystems#28]
Hi all,

Installed this repo via HACS. I can now see the sensors but it’s not appearing in the list of devices. Is this normal?

Thanks!

**Comment by skelgaard** [comment]
There will be a new version tomorrow that should fix some of the issues... please make a new report with debug  logs if it still doesn't work
logger:
  default: info
  logs:
    custom_components.apsystems: debug
