### ISSUE TITLE
Three ecuId，how to set configuration.yaml.

### ISSUE THREAD

**Issue by wzq02168** [skelgaard/homeassistant-apsystems#33]
1、My account is logged in from www.apsystemsema.cn, not www.apsystemsema.com.
I changed the sensor.py sentence after 246 and 247 lines, can be used.
2、I have three ecuId，How to set configuration.yaml.
`sensor:
  - platform: apsystems
    authId: apsystemsem_authid
    systemId: apsystemsema_system_id
    ecuId: apsystemsema_ecu_id_1
    sunset: off

sensor:
  - platform: apsystems
    authId: apsystemsem_authid
    systemId: apsystemsema_system_id
    ecuId: apsystemsema_ecu_id_2
    sunset: off

sensor:
  - platform: apsystems
    authId: apsystemsem_authid
    systemId: apsystemsema_system_id
    ecuId: apsystemsema_ecu_id_3
    sunset: off`

This setting only has the first user effect.

**Comment by skelgaard** [comment]
sorry but i have no way to test this, so nothing i can do... you are welcome todo a PR for a fix for this or a fork and do your own version :)
