### ISSUE TITLE
Energy section not seeing Solar until after 3pm

### ISSUE THREAD

**Issue by gwilliams1205** [skelgaard/homeassistant-apsystems#35]
Over the last 2 weeks something appears to have changed in the way the system does polling.. My sensors are now staying dormant until around 3pm every day.. Then just showing what has been produced until then. I thought it was the sunset setting, but I changed that to off with no difference.
![image](https://github.com/skelgaard/homeassistant-apsystems/assets/31353903/d1f2c401-0ccb-4ad7-939b-134101e2d6e1)

The sensors also shows the wrong date until after 3pm again:

![image](https://github.com/skelgaard/homeassistant-apsystems/assets/31353903/29de1c2a-bb28-4ee5-ae83-fb750a96d727)

Please help

**Comment by skelgaard** [comment]
whats is your timezone ?

you need to test their api and look what you get back from it...
here are the raw requests

place replace the 3 Uppercase names with your own ids to test them.
There should be no private info in the output, but please check it before posting it
Login

GET https://www.apsystemsema.com/ema/intoDemoUser.action?id=APSYSTEMS_AUTH
Get Data

POST https://www.apsystemsema.com/ema/ajax/getReportApiAjax/getPowerOnCurrentDayAjax

queryDate=20240317&selectedValue=APSYSTEMS_ECU&systemId=APSYSTEMS_ID

**Comment by skelgaard** [comment]
well that means their API is down and then it doesn't work... it will then pick up the "slack" when it comes up
does https://apsystemsema.com work for you ?

**Comment by gwilliams1205** [comment]
It was working fine then something changed about 2 weeks ago.. Have you not seen any changes?

**Comment by skelgaard** [comment]
well i can't say then.... if you look at network traffic when going to their site, its the same url with the same parameters i call.
no mine is working fine.
This is mine from today
![billede](https://github.com/skelgaard/homeassistant-apsystems/assets/13235820/b2eb071d-09ed-4a9c-8a56-5a4a953ba41e)

**Comment by skelgaard** [comment]
btw you need todo thoose post in postman or something like that, as it needs info from the first in the second call

**Comment by gwilliams1205** [comment]
I am using postman.. is there any special setting I need set to make sure it's looking at the response from the GET when sending the POST?

**Comment by skelgaard** [comment]
nope that should work fine then, but the problem is the connection to their API... its always that when it is and as long as EMA don't let us fetch that data direct from their router, then there is no other way to get the data, unless you get a shelly or something else to messure it.

**Comment by gwilliams1205** [comment]
well that's less than Ideal..

Thanks for the help though.. It just stinks it was working great then decided to stop all of a sudden

**Comment by skelgaard** [comment]
i wish there was something i could do, but if your not able to pull data from their api, then neither can home assistant and that will give the graph you showed.
